/* PCMatch app. Configure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in config.js. */
let currentRole = 'buyer';
let currentUser = null;
let selectedRequestId = null;
let requests = [
 {id:'req-101',title:'PC para gaming competitivo y edición básica',category:'PC armada',use_case:'Gaming',budget:'S/ 4,000',city:'San Miguel, Lima',details:'Quiero jugar Valorant y Fortnite en buena calidad. También editar videos cortos. Ya tengo monitor Full HD.',status:'published',created:'Hace 12 min'},
 {id:'req-102',title:'Upgrade para PC con Ryzen 5 3600',category:'Upgrade',use_case:'Trabajo',budget:'S/ 1,500',city:'Surco, Lima',details:'Tengo 16 GB RAM y GTX 1660. Busco mejorar rendimiento para AutoCAD y renderizado ligero.',status:'published',created:'Hace 38 min'},
 {id:'req-103',title:'Laptop o PC compacta para diseño gráfico',category:'PC armada',use_case:'Diseño y edición',budget:'S/ 3,300',city:'Miraflores, Lima',details:'Uso Illustrator, Photoshop y Figma. Necesito garantía y entrega esta semana.',status:'quoting',created:'Hace 1 h'}
];
let quotes = [
 {id:'quo-201',request_id:'req-101',seller:'TechCore Perú',seller_id:'seller-demo',price:'S/ 3,890',config:'Ryzen 5 5600 · RTX 4060 · 16 GB RAM · SSD 1 TB',warranty:'12 meses',delivery:'24–48 horas',status:'sent',rating:'★ 4.8'},
 {id:'quo-202',request_id:'req-101',seller:'Zona Gamer',seller_id:'seller-2',price:'S/ 4,090',config:'Ryzen 5 5600X · RTX 4060 · 32 GB RAM · SSD 1 TB',warranty:'18 meses',delivery:'Hoy',status:'sent',rating:'★ 4.9'}
];
const $=id=>document.getElementById(id);
function moneyLabel(x){return x||'Sin presupuesto indicado'}
function openApp(label){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');$('identity').textContent=label;renderAll()}
function enterDemo(role){currentRole=role;currentUser={id:role+'-demo',name:role==='buyer'?'Valeria M.':'ByteLab Perú',email:role==='buyer'?'valeria@ejemplo.pe':'ventas@bytelab.pe',phone:role==='buyer'?'+51 987 654 321':'+51 955 123 456'};openApp(`Demo: ${role==='buyer'?'Comprador':'Vendedor verificado'}`)}
window.enterDemo=enterDemo;
function renderAll(){renderMarket();renderQuotes();renderProfile();}
function renderMarket(){const isBuyer=currentRole==='buyer';$('marketView').innerHTML=`<div class="panel-head"><div><h1>${isBuyer?'Mis solicitudes':'Solicitudes disponibles'}</h1><p class="muted">${isBuyer?'Publica lo que necesitas y compara propuestas sin revelar tu contacto.':'Revisa las necesidades publicadas y cotiza solo las que puedas atender.'}</p></div>${isBuyer?'<button class="btn primary" onclick="requestModal.showModal()">+ Publicar solicitud</button>':'<button class="btn outline" onclick="renderMarket()">↻ Actualizar</button>'}</div><div class="stats"><div class="stat"><b>${isBuyer?requests.length:requests.filter(r=>r.status!=='closed').length}</b><small>${isBuyer?'Solicitudes activas':'Solicitudes abiertas'}</small></div><div class="stat"><b>${isBuyer?quotes.filter(q=>q.request_id==='req-101').length:'4.8'}</b><small>${isBuyer?'Cotizaciones recibidas':'Mi calificación'}</small></div><div class="stat"><b>${isBuyer?'0':'12 min'}</b><small>${isBuyer?'Contactos desbloqueados':'Tiempo de respuesta'}</small></div></div><div class="tabs"><button class="tab active">${isBuyer?'Todas':'Recién publicadas'}</button><button class="tab">${isBuyer?'Con ofertas':'Compatibles conmigo'}</button></div><div class="request-grid">${requests.map(r=>requestCard(r,isBuyer)).join('')}</div>`}
function requestCard(r,isBuyer){const requestQuotes=quotes.filter(q=>q.request_id===r.id);return `<article class="request"><div class="request-top"><div><h3>${r.title}</h3><span class="muted" style="font-size:12px">${isBuyer?'Tu solicitud':'Comprador PCMatch'} · ${r.created}</span></div><span class="tag ${r.status==='quoting'?'orange':'green'}">${r.status==='quoting'?'Recibiendo ofertas':'Abierta'}</span></div><p>${r.details}</p><div class="meta"><span class="tag blue">${r.category}</span><span class="tag">${r.use_case}</span><span class="tag">${r.budget}</span><span class="tag">⌖ ${r.city}</span></div><div class="actions">${isBuyer?`<button class="btn primary" onclick="showQuotes('${r.id}')">Ver ${requestQuotes.length} cotización${requestQuotes.length===1?'':'es'}</button>`:`<button class="btn primary" onclick="openQuote('${r.id}')">Enviar cotización</button>`}<span class="lock">🔒 Contacto protegido</span></div></article>`}
function renderQuotes(){const isBuyer=currentRole==='buyer';const relevant=isBuyer?quotes:quotes.filter(q=>q.seller_id==='seller-demo');$('quotesView').innerHTML=`<div class="panel-head"><div><h1>${isBuyer?'Cotizaciones recibidas':'Mis cotizaciones'}</h1><p class="muted">${isBuyer?'Compara cada propuesta. El contacto solo se habilita si aceptas una.':'Sigue el estado de tus propuestas y responde con claridad.'}</p></div></div><div class="quote-list">${relevant.length?relevant.map(q=>quoteCard(q,isBuyer)).join(''):'<div class="empty">Aún no hay cotizaciones en este perfil de demostración.</div>'}</div>`}
function quoteCard(q,isBuyer){const r=requests.find(x=>x.id===q.request_id);const accepted=q.status==='accepted';return `<article class="quote"><div class="quote-head"><div><h3>${isBuyer?q.seller:r?.title}</h3><span class="muted" style="font-size:12px">${isBuyer?`${q.rating} · Vendedor verificado`:'Solicitud de comprador PCMatch'}</span></div><div style="text-align:right"><span class="price">${q.price}</span><br><span class="tag ${accepted?'green':'blue'}">${accepted?'Aceptada':'Enviada'}</span></div></div><div class="quote-detail"><div><span>Propuesta</span><b>${q.config}</b></div><div><span>Garantía</span><b>${q.warranty}</b></div><div><span>Entrega</span><b>${q.delivery}</b></div></div><div class="actions">${isBuyer?(accepted?`<button class="btn primary" onclick="unlockContact('${q.id}')">Ver contacto</button>`:`<button class="btn primary" onclick="acceptQuote('${q.id}')">Aceptar cotización</button>`):`<span class="lock">${accepted?'🔓 Contacto disponible':'🔒 Esperando decisión del comprador'}</span>`}</div></article>`}
function renderProfile(){const isSeller=currentRole==='seller';$('profileView').innerHTML=`<div class="panel-head"><div><h1>Mi perfil</h1><p class="muted">${isSeller?'Tu perfil genera confianza antes de que un comprador acepte una cotización.':'Mantén tus datos actualizados para desbloquear contacto de forma segura.'}</p></div></div><div class="profile-box"><span class="state">${isSeller?'Vendedor verificado':'Cuenta autenticada'}</span><h3 style="margin:10px 0 5px">${currentUser.name}</h3><p class="muted">${currentUser.email} · ${currentUser.phone}</p></div>${isSeller?'<div class="profile-box"><h3 style="margin:0 0 8px">Indicadores de desempeño</h3><p class="muted">La versión real mostrará propuestas enviadas, tiempo de respuesta, conversiones, calificaciones y solicitudes atendidas.</p></div>':'<div class="profile-box"><h3 style="margin:0 0 8px">Privacidad del comprador</h3><p class="muted">Tu correo y WhatsApp no se muestran en una solicitud pública. Solo se revelan luego de aceptar una cotización.</p></div>'}`}
function switchView(view){['market','quotes','profile'].forEach(v=>{$(v+'View').classList.toggle('hidden',v!==view)});document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function showQuotes(id){switchView('quotes');const first=quotes.find(q=>q.request_id===id);if(!first){$('quotesView').innerHTML='<div class="empty">Todavía no recibes cotizaciones para esta solicitud.</div>'}}
window.showQuotes=showQuotes;
function openQuote(id){selectedRequestId=id;const r=requests.find(x=>x.id===id);$('quoteRequestTitle').textContent=r.title;$('quoteNotice').style.display='none';$('quoteModal').showModal()}
window.openQuote=openQuote;
$('requestForm').addEventListener('submit',e=>{e.preventDefault();requests.unshift({id:'req-'+Date.now(),title:$('rTitle').value,category:$('rCategory').value,use_case:$('rUse').value,budget:$('rBudget').value,city:$('rCity').value,details:$('rDetails').value,status:'published',created:'Ahora'});$('requestNotice').style.display='block';renderMarket();setTimeout(()=>$('requestModal').close(),900);e.target.reset()});
$('quoteForm').addEventListener('submit',e=>{e.preventDefault();quotes.unshift({id:'quo-'+Date.now(),request_id:selectedRequestId,seller:'ByteLab Perú',seller_id:'seller-demo',price:$('qPrice').value,config:$('qConfig').value,warranty:$('qWarranty').value,delivery:$('qDelivery').value,status:'sent',rating:'★ 4.7'});const r=requests.find(r=>r.id===selectedRequestId);if(r)r.status='quoting';$('quoteNotice').style.display='block';renderAll();setTimeout(()=>$('quoteModal').close(),900);e.target.reset()});
function acceptQuote(id){quotes.forEach(q=>{if(q.request_id===quotes.find(x=>x.id===id).request_id)q.status=q.id===id?'accepted':'not_selected'});renderQuotes();renderMarket();unlockContact(id)}
window.acceptQuote=acceptQuote;
function unlockContact(id){const q=quotes.find(x=>x.id===id);const isBuyer=currentRole==='buyer';$('contactName').textContent=isBuyer?q.seller:'Valeria M.';$('contactInfo').textContent=isBuyer?'WhatsApp: +51 955 123 456 · ventas@techcore.pe':'WhatsApp: +51 987 654 321 · valeria@ejemplo.pe';$('contactModal').showModal()}
window.unlockContact=unlockContact;
$('signOut').addEventListener('click',async()=>{if(window.pcmatchSupabase) await window.pcmatchSupabase.auth.signOut();$('app').classList.add('hidden');$('loginScreen').classList.remove('hidden')});
$('googleLogin').addEventListener('click',async()=>{if(!window.pcmatchSupabase){alert('Para activar Google, agrega la URL y la clave publicable de Supabase en config.js. Mientras tanto puedes recorrer el modo demostración.');return}const {error}=await window.pcmatchSupabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+window.location.pathname}});if(error)alert(error.message)});
async function restoreSupabaseSession(){
  if(!window.pcmatchSupabase)return;
  const {data:{session}}=await window.pcmatchSupabase.auth.getSession();
  if(session){const u=session.user;currentUser={id:u.id,name:u.user_metadata?.full_name||u.user_metadata?.name||'Usuario PCMatch',email:u.email,phone:''};currentRole='buyer';openApp(`Conectado: ${currentUser.name}`)}
  window.pcmatchSupabase.auth.onAuthStateChange((_event,sessionNow)=>{if(sessionNow&&!currentUser){const u=sessionNow.user;currentUser={id:u.id,name:u.user_metadata?.full_name||u.user_metadata?.name||'Usuario PCMatch',email:u.email,phone:''};currentRole='buyer';openApp(`Conectado: ${currentUser.name}`)}});
}
restoreSupabaseSession();
